Repository ZingZing001/G9_CanvasPlus, pull requests merged in 2025-08, with the labels that each got.

#1 Add issue and pull request templates
  template/ISSUE_TEMPLATE.md
  template/PULL_REQUEST_TEMPLATE.md
Labels: documentation, maintenance

#4 Made frontend grid component.
  ibras-stuff/.gitignore
  ibras-stuff/README.md
  ibras-stuff/eslint.config.js
  ibras-stuff/index.html
  ibras-stuff/package-lock.json
  ibras-stuff/package.json
  ibras-stuff/public/vite.svg
  ibras-stuff/src/App.css
  ibras-stuff/src/App.jsx
  ibras-stuff/src/assets/react.svg
  ibras-stuff/src/components/Widget.jsx
  ibras-stuff/src/components/WidgetGrid.jsx
  ibras-stuff/src/components/WidgetGridContext.jsx
  ibras-stuff/src/index.css
  ibras-stuff/src/main.jsx
  ibras-stuff/vite.config.js
  package-lock.json
Labels: A1

#5 Tidied up the file structure and set up an entry point (server) for backend integration
  client/.gitignore
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.jsx
  client/src/assets/react.svg
  client/src/components/WidgetGrid.jsx
  client/src/index.css
  client/src/main.jsx
  client/vite.config.js
  package-lock.json
  package.json
  server/placeholder.txt
  src/index.js
Labels: maintenance

#11 updating the documentation with the issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  ISSUE_TEMPLATE/custom.md
Labels: A1, documentation

#28 Feature/clock
  client/setupTests.js
  client/src/App.css
  client/src/App.jsx
  client/src/components/ClockWidget.jsx
  client/src/components/WidgetGrid.jsx
  client/src/css/base.css
  client/src/css/clock.css
  client/src/hooks/useGoogleCalendarEvents.js
  client/src/test/ClockWidget.test.jsx
  client/vitest.config.js
Labels: A1, feature, Testing

#39 updated the testing in readme
  README.md
Labels: A1, documentation, low priority

#19 Feature/gpt wrapper widget
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/GptWrapper.jsx
  client/src/hooks/useGoogleCalendarEvents.js
  client/src/test/GptWrapper.test.jsx
  package-lock.json
  package.json
  server/src/main/java/nz/ac/uoa/g9/backend/ai/LLMController.java
  sonar-project.properties
Labels: A1, feature
